name: BQ Discovery Compare docs tests
on:
  push:
    paths:
      - scripts/comparedocs

# TODO change repo
# TODO change token to yoshi one
jobs:
  open-issue:
    if: ${{ github.repository == 'leahecole/discovery-artifact-manager' }} 
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: execute
        run: |
           python scripts/comparedocs/discovery_comparer/discovery_test.py
